### ISSUE TITLE
Create consumer group during test initialization

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-event-hubs-dotnet#14]
Running the tests locally (brand new storage account and EventHub namespace) results in failing tests.

![image](https://cloud.githubusercontent.com/assets/1309622/19332834/201a8f92-90ad-11e6-8d7d-baaa879d5e29.png)

/cc @serkantkaraca

**Comment by jtaubensee** [comment]
Hi @SeanFeldman - All tests show as passing for me at the moment. One thing to keep in mind is that currently there are tests that require the manual creation of a consumer group in order to succeed. One of which is "MultipleConsumerGroups."

Let's leave this issue open as a reminder to add the proper setup to our tests so that there is no advanced manual configuration required.

**Comment by SeanFeldman** [comment]
> currently there are tests that require the manual creation of a consumer group in order to succeed

That all should be captured in the `readme.md` under Getting Started section. Without instructions it's hard to contribute.

**Comment by serkantkaraca** [comment]
Only MultipleConsumerGroup test requires custom consumer group. I will add proper instructions on this.

**Comment by SeanFeldman** [comment]
@serkantkaraca when you do, could you please ping here? Thank you.

**Comment by SeanFeldman** [comment]
@serkantkaraca also `cgroup1`.
IMO these consumer groups should be created during tests initialization.

**Comment by serkantkaraca** [comment]
Client doesn't support management operations yet. Consumer group needs to be created manually for now. I will just add a reminder in the unit testing section.

**Comment by SeanFeldman** [comment]
👍 @serkantkaraca I presume by "add a reminder in the unit testing section" you mean an instruction step :) Thank you.

**Comment by serkantkaraca** [comment]
Correct.

**Comment by jtaubensee** [comment]
Closing based on #32. As we develop the client further, we will need to decide which management operations are available in this client, as they are available in the event hubs management client. (https://www.nuget.org/packages/Microsoft.Azure.Management.EventHub). Generally speaking, it is not considered a best practice to create Event Hub entities on the fly during run time, which is why they are currently separated.
