### ISSUE TITLE
CancellationToken on async calls?

### ISSUE THREAD

**Issue by nrandell** [Azure/azure-event-hubs-dotnet#156]
Are there any plans to add support for CancellationTokens passed into calls? I'm using this library from Service Fabric and really need to be able to cancel calls.

I couldn't find any reference to cancellation tokens in the sending path. There appeared to be a few in the receiving path.

**Comment by serkantkaraca** [comment]
AQMP library doesn't support CancellationToken, therefore we can't as well. Event Hub calls are IO calls so cancelling a call doesn't give you any guarantee. Relying on the Timeout model is more solid in this sense. Let me know if you have any questions.

**Comment by nrandell** [comment]
Ok thanks. This surprises me given that the HttpClient performs IO and support cancellation tokens. Is this something that you think the AMQP library should support?

**Comment by serkantkaraca** [comment]
HTTP is a way broader protocol then ours and expected behavior might drastically change depending on what type of server the client is talking to. Such as uploading large files or requesting a small JSON. On the other hand, we are implementing a messaging protocol and our API calls shouldn't last longer than split second in most cases. There is not much to cancel in that sense actually. 

I would like to know how would cancelling EventHubs calls help for Fabric integration? If I know what you are trying to achieve may be I might help.

**Comment by nrandell** [comment]
Within Fabric your service gets cancelled when a service partition needs to be moved. In order to keep the service availability as high as possible, the service should really cancel within 4 seconds. Cancellation of a service is signalled through a cancellation token which could be passed to other calls, or used to trigger another cancellation token. Also within service fabric it is possible for one host application to host multiple services, so we can't even exit the application.

On a different project I've recently seen the occasional Timeout Exceptions and I've switched to setting the RetryPolicy to NoRetry and using the [Polly library](https://github.com/App-vNext/Polly) to handle retries in a different manner. Whilst doing that I was looking to pass a cancellation token in, so it could be cancelled if required. 

This caused me to raise this issue and as I'm beginning to use Event hubs more and more in my Service Fabric applications used this as an example of where a cancellation token is important. There are ways of working around it, but they are not as clean as just being able to cancel a task.

I hope this makes sense. Let me know if you need any more information.

**Comment by xinchen10** [comment]
@nrandell The desired way to shutdown protocol state machines of the client is to close the connection, instead of cancelling outstanding operations. You should have a reference to the EventHubClient object. In case of service shutdown, you can close the client object which in turn shuts down and cleans up all protocol states on the client, including canceling the outstanding operations.

**Comment by nrandell** [comment]
@xinchen10 - superb! Thank you.
