### ISSUE TITLE
Send a batch to the eventhub

### ISSUE THREAD

**Issue by dauledk** [Azure/azure-event-hubs-dotnet#161]
Hi everyone, I hope you can help me with this. 

How can I send a batch of events to the eventhub?

I am currently using this method for singel events:
 
EventHubClient eventHubClient = EventHubClient.CreateFromConnectionString(
    _eventHubSettings.ConnectionString,
    _eventHubSettings.Name
);
 
eventHubClient.Send(eventData);

**Comment by mikhailshilkov** [comment]
Just use an overload of the same `Send` method which accepts `IEnumerable<EventData>`.

**Comment by thomasclaudiushuber** [comment]
Just wanted to add that you should use the EventDataBatch to create the IEnumerable<EventData> if you want to ensure that you keep the 256KB/message size limit for your batch. (For standard Event Hub, dedicated has 1024KB limit).
Create a batch like this:
var batch = EventHubClient.CreateBatch();
then use batch.TryAdd to add EventData objects and use batch.ToEnumerable() to get the IEnumerable<EventData> that you can give to the Send/SendAsync method.

The advantage here is that EventDataBatch takes care of the message size limit of 256KB for a standard Event Hub. When TryAdd returns false, that means that the 256KB are exceeded. Then, send the batch and create a new one for the not send messages.

**Comment by riccardo91** [comment]
@thomasclaudiushuber batch.TryAdd can be used in concurrent environment? For example 
batch.TryAdd in Asp.net Pageload with 500 client request per seconds?

**Comment by thomasclaudiushuber** [comment]
@riccardo91 I think it's worth a try. I always use it when batching. The only thing it does is to ensure that the size doesn't exceed. But if you're sure that you're by far below the 256kb limit, you can decide if you want to use it or not.

**Comment by riccardo91** [comment]
@thomasclaudiushuber assume that we have an Asp.net Page that at load time send an event to Azure Hub. What is the best practice for high scalability?

1)Send an Event at each request
2)Singleton that collects Events for each request in Memory and flush them each (n) seconds with sendBatch?
3)Other?
Thanks

**Comment by riccardo91** [comment]
Thanks for feedback:
1) fire and forget it's usually not a good practice in Asp.net.
2)We can achieve the static client in this way. Not sure what happen if connection is lost() nothing in the documentation.
```
   private static readonly Lazy<EventHubClient> LazyConnection
      = new Lazy<EventHubClient>(() =>
      {
          var connectionStringBuilder = new EventHubsConnectionStringBuilder("****************")
          {
              EntityPath = "****",
          };

          EventHubClient client = EventHubClient.CreateFromConnectionString(connectionStringBuilder.ToString());

          return client;
      });
    public static EventHubClient Connection
    {
        get
        {
            return LazyConnection.Value;
        }
    }
```

3)How would you create batch when you reach the Max size without using a lock that will affect performance in asp.net env?

 public static async Task Send(string id, string rowkey)
    {


        
        if (LazyBatch.Value.TryAdd(new EventData(Encoding.UTF8.GetBytes("{\"id\":\"" + id + "\"}"))))
        {
            await semaphoreSlim.WaitAsync();
            try
            {
                await Connection.SendAsync(LazyBatch.Value.ToEnumerable());
            }
            finally
            {
               
                semaphoreSlim.Release();
            }
           
           
        }

    }

**Comment by davidrevoledo** [comment]
@riccardo91 

I share my personal experience with the sdk of course @serkantkaraca can answer properly your concerns, but it might help. 

1) I think fire and forget make sense when you don't need information about a task competition, I understand what you mean that asp.net is not the ideal place to do background work because the architecture of it, what about if you consider use a webjob instead ? 

2) The client has a method that close the internal connection if the connection was lost, 
https://github.com/Azure/azure-event-hubs-dotnet/blob/ee96547b7f640a97199cec91840eea2ce9ff3e51/src/Microsoft.Azure.EventHubs/Amqp/AmqpEventHubClient.cs#L85
I don't see any event or mechanism to do something when that happen, perhaps override that to do some custom code, I don't know if @serkantkaraca knows a better way to be notified externally when a connection is closed.

3)  That's a good one, personally I've implemented something like that with a internal buffer but it has a lock to do thread safe, I cannot imagine a way now to do that. 
I found this article that seems to be interesting http://www.adammil.net/blog/v111_Creating_High-Performance_Locks_and_Lock-free_Code_for_NET_.html
