### ISSUE TITLE
the Microsoft.Azure.Device.DeviceClient can set the Property „iothub-connection-device-id“ 

### ISSUE THREAD

**Issue by floec** [Azure/azure-event-hubs-dotnet#183]
when the Microsoft.Azure.Device.DeviceClient does not set the Property „iothub-connection-device-id“, this key-value shows the correct value

when the Microsoft.Azure.Device.DeviceClient sets the Property „iothub-connection-device-id“, this key-value shows an incorrect value

so the Property „iothub-connection-device-id“ cannot be used for validation.

Is this the expected behaviour?

[sample.zip](https://github.com/Azure/azure-event-hubs-dotnet/files/1161320/sample.zip)

**Comment by serkantkaraca** [comment]
Do you mean the property set on the sender missing on the receiver?
Does this scenario work with .Net client?

**Comment by serkantkaraca** [comment]
OK, I was able to run your sample code. The message property mapping between .NET and .Net Standard clients are different. I will check the codes and update the thread.

**Comment by serkantkaraca** [comment]
Identified the bug in the client. The fix will be released as part of our next client release, most probably next week. Thx for pointing the issue.

**Comment by floec** [comment]
Thanks for looking into it.

**Comment by serkantkaraca** [comment]
Update on the issue. Consensus was this is by design. IOT developer needs to know about IOT reserved properties and refrain from using it on the sender. Does it work for you if you change the property name?

**Comment by serkantkaraca** [comment]
Marking this as bug. We will make sure IOT set properties aren't overwritten by application properties which set on the sender client. The fix will be shipped in the next release.

**Comment by floec** [comment]
Due to bug fix not released yet, using Nuget package WindowsAzure.ServiceBus.

**Comment by serkantkaraca** [comment]
Fix PR https://github.com/Azure/azure-event-hubs-dotnet/pull/206

**Comment by skyflyer** [comment]
@serkantkaraca, please correct me if I'm wrong, but it seems to me, that "device-to-cloud" messages, sent to Azure IoT hub should not be allowed to "spoof" their device-id by setting `iothub-connection-device-id` property in any way.

In other words, I expect that the device id I retrieve from the `EventData` properties corresponds to the actual device that sent it. Otherwise, this could pose a security risk.

Of course, I am not talking about the client libraries only; this should be something that IoT Hub would enforce for all possible ingress protocols (MQTT, AMQP, HTTP, ...).

What are your thoughts on that?

**Comment by serkantkaraca** [comment]
Fix is merged now.
