### ISSUE TITLE
Out of retries creating lease for partition

### ISSUE THREAD

**Issue by fvenezia** [Azure/azure-event-hubs-dotnet#299]
Hi,
I get 'Out of retries creating lease for partition' whenever I try to use RegisterEventProcessorAsync method on EventProcessorHost class, even with .NET sample project at https://github.com/Azure/azure-event-hubs/tree/master/samples/DotNet/Microsoft.Azure.EventHubs
 
My connection strings are good since the client sample works fine.

Thanks for your help

**Comment by serkantkaraca** [comment]
I have just moved the sample to SDK 2.1. Can you download and try again?

**Comment by fvenezia** [comment]
I found the problem : the storage account was general purpose v1, I changed to blob storage and now it works fine.
I suggest to set a more accurate message to the exception when storage account API fails.
Thank you.

**Comment by serkantkaraca** [comment]
Thx for pinpointing the issue. I will find out if we can improve the error message.

**Comment by babin93** [comment]
Hi,
Could the last retry failure reason be included as an inner exception of the exception returned ? I had to debug for a while and checkout the EventProcessorHost to figure out that my problem that was not occuring all the time was caused by a too low version of NewtonSoft.Json that I was using. If the error message would have been included with the error, It would have been way easier for me to figure out what was my issue.

Thank you !

**Comment by serkantkaraca** [comment]
Sure, I will look at that.

**Comment by serkantkaraca** [comment]
PR https://github.com/Azure/azure-event-hubs-dotnet/pull/314

**Comment by serkantkaraca** [comment]
SDK 2.2 is released with this fix.
