### ISSUE TITLE
Getting duplicate events from eventhub in eventtrigger azure function

### ISSUE THREAD

**Issue by JayeshSonawane-GEP** [Azure/azure-event-hubs-dotnet#358]
## Actual Behavior
1. Event trigger azure function should checkpoint and process 1 event only one time. 

## Expected Behavior
1. Event trigger function is getting duplicate events 

## Versions  
- OS platform and version: Azure function c#
- .NET Version: 4.6
- NuGet package version or commit ID: 2.2.1

**Comment by JayeshSonawane-GEP** [comment]
This is bit urgent. Please look into this.

**Comment by serkantkaraca** [comment]
Event Hubs provides 'at least once' delivery guarantee. As I understand you are looking for 'exactly once'. Please work with Azure Functions Team and see if they an reduce the duplicates.

**Comment by serkantkaraca** [comment]
Your code looks OK. I think you need to answer this. Do you need zero duplicates or less number of duplicates? Zero-duplicates is impossible w/o transactional write and read which Azure Event Hubs lacks it today as a feature. However, I believe there is always room to reduce number of duplicates.

**Comment by JayeshSonawane-GEP** [comment]
I need zero duplicates. can you please suggest some code reference for transnational write?

**Comment by serkantkaraca** [comment]
Azure Event Hubs doesn't support transactions. I wonder if Azure Functions supports Service Bus queues/topics since that one supports transactions.

**Comment by JayeshSonawane-GEP** [comment]
It looks we will have to move on SB.

**Comment by simonsabin** [comment]
You have to have some idempotency checking in you function. When scaling happens the new scale unit will take over processing a partition and thus reprocess the same messages. You can checkpoint for each message but the problem is one can end up then loosing messages. 

The easiest option is to implement a redis cache to that records if an event has been processed. or some other checking process.
